### ISSUE TITLE
Cannot show Sars Cov 2 protein S 

### ISSUE THREAD

**Issue by dridk** [joiningdata/lollipops#50]
Hi,

I try to show protein S , but I didn't success ! 

https://www.ncbi.nlm.nih.gov/gene/43740568

**Comment by pbnjay** [comment]
Please share the command you used and what the error message was.

**Comment by pbnjay** [comment]
So there's a couple things going on, first that's an Ensembl Identifier so the invocation would actually be:
`lollipops -Q ENSEMBL_ID ENSSASG00005000004`

Second, there seems to be some issues linking the identifier to Pfam domains. The UniprotKB accession is `P0DTC2` but there are no Pfam protein entries for it: http://pfam.xfam.org/protein/P0DTC2

Until it's annotated by Pfam we can't do much easily since we don't know the domain layout. In the meantime, if you know the structure you can edit an existing example (e.g. for http://pfam.xfam.org/protein/U5LNM4 you can save the domain architecture found at http://pfam.xfam.org/protein/U5LNM4/graphic to a local file). After you make your changes you can use `-l=yourfile.json` to draw the figure.

Hope that helps!
